#endpoints:
#  hypermedia:
#    enabled: true

info:
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @maven.compiler.source@
      target: @maven.compiler.target@
# removed (now using build-info-goal from maven plugin (see pom.xml))
#    project:
#      name: '@project.name@'
#      groupId: @project.groupId@
#      artifactId: @project.artifactId@
#      version: @project.version@

management:
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: '*'
#  security:
#    enabled: true
##    roles: 'ACTUATOR, SUPERUSER'
  server:
    port: 9001
#    servlet:
#      context-path: '/monitoring'

#security:
#  basic:
#    enabled: false
#  headers:
#    cache: false

spring:
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: "USER, ACTUATOR"
  thymeleaf:
    cache: false

server:
  port: 9000
  server-header: "@project.name@ v@project.version@"
  servlet:
    context-path: "/"

---

#management:
#  security:
#    enabled: true

spring:
  profiles: PROD
  thymeleaf:
    cache: true