language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack:
    secure: JAwqGHzdCyvon8kGTSOno+bf0+suIcvWyjx+W6vPd3tCFH/h+gYPRqoNlGh6HazHoOVJRzz8EuTQlHLrhnGZTe7Fien4L9f2beMXTpErBsdiPDKYYPjwYUVJ49E5VO6eUeLjWwFF2EbLGBCfAOAo1izG8xK/9jXwywivo0N/QjZaYAePN38++25jCe1ROLS96LtBjdVlfrQV8qPgF0mZpRGhthLRqj56bGUFsNPakCUuyqBQm41uqjEdA2MghdYsnMVQhJljhY7I2ov9HnRZ98c/oHSX7U9To77EjZxbvxUcF59M/IbGnlbKD2CVNGyU3+4wPIKfup9bhTKFoPxne2kZxeqycM7nKXgFU59ieyTzgVeOOyJsnqx5Bk01i8+/lBJSNarZ89vF7Wxh6rac5/QOu4WtCOBVlWW2Vli0Op/sE6O3F4rsov41+7DwEHeQCas93Tsi6MAfIQcB7bl6wfO2g4X3JlWk4sqliUcyzBWypMCIxTzyEU3hXrwaeJbIFhUfs86zuKRgFuvyNQiHzl7YOygJGZGNDYDpSThqto0hwlM+bgnO3EuoHzbq+Ym4eAyYoulmK1wzYIOcwMz80YGrkIjRrP7sLDtRticdx9NQiVkdTFJkNk4h2crHaKWvD1EJ8DDyKWiBbRQjfX5jw19MF/aAlzvq4VCDI3p6+kg=
  email:
  - anthony.denecheau@gmail.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: sBssUffzEBe2M4l+SeMQOTsuO/SdCidqJo7bsRocQ10oY4hku7yM2g2pqUGkLUe/msFZZ4/mjKbpVOlB8YmmWyHGJShbf4AwkH3jRXyJ/Mbda19J4l7/Cd1f82kzUeavYrq/dnoZ/yoJtzklYx2+C3OjO+zh5kwGVKANXIHiVHDR25S5bNqt4B19StMijjPsVAaK9/J6xOgcwG0hAjSgYuZnVdiJJOkNwNqVuF8REuIMrfDVL31uAOezc/iu7Msv2kcsXR7xFM7haJJa64+/QzyDwogKxIq7AbLnVLxc/yl+vav1oaOaw0Gb72OxLT1q/qNlAqQm0FhtyVC6trPyFMNArtamcOX3eszST3gPuA2li4gdPq5V0arcGXyH35ok7TFIrURTHqKWEp//VdL2v9FJ/4QHatAz4OAWq9REgtNRINJ8I139+Zl6lxQnXMaZdkPR+jBm0sM3O7tX5nPtQ+UvEvKWDt2r5EYrCkSX5o0afpdLKEhIra61Nji30O8BmmFR/3CCaxwZ2GXTumYsOHoTfmwjUOWoiWzBqdDYOw3RVqJgXGron9MqVW7qNLlTfavD/7Vi2Bjax144Xx04NDSalTOanNneFO6qcjfyOCLIYTh5e/3YGRB5G1SXVxrOUP1LS/+Q/v/7GazeXhbylTawQz9MfIOcRjKr5p8Cb6w=
  - secure: I5wZEIM74YjThtUlxDfbRXuZm2bGa5K/bFV+llOz0GQ93V5G6TLdJcUlOYPmYOr2JsYRt8ZD6e7EOWurmecUi9tbmGph30e82ff9N/FImmdeAA2YG17FxG7mRQqYfUcQLIAIFa5+mLw0SmAdqgeh2Tul1Q7zBsR4mame/ok6MG9PGnhgYQXgchX7uWZ/4xU7TpuWMsW3JlYSUuMZSy4Qu3KVHI82ZGQtYLcJTQdJ5QWV/bEivg4ne4eEW6ZR1cC1Why+LLlq/YK8+DndvbBxAB4tsjpZxcK2dPupcfypg6Fgyr7acGbsVSukmsQFrllAEKsy95f4sZ3sXCcd30kA4AxSJaJAPw+9muDDOZLub/YjNt+HWwutHkMpZZsubilXN1MKB8/znVjY8Nvy/h8AIw6vhie7gfepxBGF296ElfiHMs6VBc+Ab/WYYf1qNB4AS+xCq/8S14zu9jbV4d3pMrg4Zm1oa7hGa9wNn/rkMe8y2OUVIw2+HadYX7NWsPDhBxrNt8KACZDZK8y5CoI9qmQOOf5CK2NEEQjoUb3w+EuzCOpu3J/vFaXrI7ypF5LbdMO7t1fZQxmxE1mC7VYdl9r4/hHS1YkSbPiKktsx4NxZvEng6Ox/sGAvJVV9awEOuRp5s1bj9tp81hpqkYHm5KhkloYJYtYAwf7+/rVWhco=
  - secure: Smk9FMJm0vYgv2WKceB2kzM0qIC7Q76THvPBGGOF7RB7SAozTMWVbj2vAA0K075QjaWRbPn4Ay4RRoJtZZJWG0G1CPW9EggJJ8k1rjNR8yKOpltjoXjpcrINRxA3aggJwfV7elHn5cNUDpWDzLG3vWp/a0mmvbFP1ibEkOyQbYYjaUnrp+LmOWVoW6R5QRusCWT3/jSdF/ydyEDigLYZgyxzHs+q9EyD6FVKcnoS89WsHh0aZ+EH11JvqtNt7XRDKrR/o+/yI7LVm/JnuHd3uYfKfpRe8m+VVXyjaqvOUyv9nUwEr9+tdnSBLBFcl3YcH2YjIyb2Z5ZfkgdEp4m4c3e4zoQZrE78D3nstjeKjXZaNHfjJBOCNL163cXagCwrQz32AyvHe//qbKIR/MgAerUd3ZkTaJLiieJJ2aIoJbbkuPyzIz35Ih5R1TMsX0Mw58Nz45RjysC7XTMDOmhGJDbLS8i4mg+CVXG5kUtDonl0IGaotJSF8vda9x4W437h/DFPNe619XDN5KlN4sNR/W9atBA4PEIDIZnqvRznohrjOCQaVFynKr5mAtriikexfVaZDr7lPVBxTal3o7D/dTUWsV+mPVaTRSiQT0gKCPNVxkFXRRilk50+4TdsfIwxMyXZ9l8NHdCVBVCV+RbSuWG/Mgy41tpjiUVNgO18ezE=
before_install:
- gem install travis -v 1.8.5 --no-rdoc --no-ri
- export BUILD_NAME=k8s-gateway-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
