language: java

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

script : 
  - mvn clean test -B
  - mvn sonar:sonar -Dsonar.organization=bfml2000-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=e75f793e839ddad69f74a9e26a6a4ad5e026031d
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
