language: java

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - lipatov.artem@mail.ru
    on_success: never
    on_failure: never