language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "buggyy-github"
    token:
      secure: "808e864843a06033b8ceb6e815be23229e7387ba"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
 email: # only send an email if build fails
  on_success: never
  on_failure: always             
