version: '2.3'
services:

  es:
    image: elasticsearch:2.4
    restart: always
#    volumes: 
#      - ${ES_PATH_DATA}:/usr/share/elasticsearch/data 
    ports:
      - 9200:9200
      - 9300:9300

  rabbit:
    image: rabbitmq:3.6-management
    restart: always
    ports:
      - 15672:15672 

  kibana:
    environment:
      ELASTICSEARCH_URL: http://es:9200
    image: kibana:4.6
    restart: always
    ports:
      - 5601:5601
    depends_on:
      - es      

  logstash: 
    image: leonardobonacci/pruning-logstash:1.0
    restart: always
    volumes: 
      - ./logstash/pipeline:/usr/share/logstash/pipeline/:ro 
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
    ports: 
      - 4560:4560
    depends_on:
      - es
      - rabbit

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: leonardobonacci/oogway-config
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 10s
      timeout: 3s
      
  orchestration-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-orchestration-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 1111:1111
      
  gateway-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-gateway-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:9090
      
  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-auth-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 5000:5000

  web-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-web-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 3333:3333
      - 8000:8000 #for debugging

  oracle-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-oracle-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      es:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 4444:4444

  sannyas-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-sannyas-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 2222:2222

  job-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-job-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8765:8765

  localtimer-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-localtimer-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 6666:6666

  money-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-money-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 11111:11111

  sentiment-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-sentiment-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 7777:7777

  weather-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      CLOUD_CONFIG_FIND_LABEL: $CLOUD_CONFIG_FIND_LABEL
      SPRING_PROFILES_ACTIVE: dev
    image: leonardobonacci/oogway-weather-service
    restart: always
    depends_on:
      rabbit:
        condition: service_started
      config:
        condition: service_healthy
    ports:
      - 9999:9999

  zipkin:
    environment:
      STORAGE_TYPE: elasticsearch
      ES_HOSTS: es
    image: openzipkin/zipkin:2.5
    restart: always
    ports:
      - 9411:9411
      
#  tor: 
#    image: osminogin/tor-simple
#    ports:
#      - 127.0.0.1:9050:9050 