version: '3'

services:

  config-service:
    build: config-service
    ports:
    - 8888:8888

  registry-service:
    build: registry-service
    ports:
     - 8761:8761

  user-authentication-service:
    build: user-authentication-service
    ports:
     - 8100:8100

  user-profile-service:
    build: user-profile-service
    ports:
     - 8101:8101