version: '3'

services:

  config-service:
    environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: gonac/config-service
    restart: always
    ports:
    - 8888:8888

  registry-service:
    environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: gonac/registry-service
    restart: always
    depends_on:
      - config-service
    ports:
     - 8761:8761

  user-authentication-service:
    environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: gonac/user-authentication-service
    restart: always
    depends_on:
      - config-service

    ports:
     - 8100:8100

  user-profile-service:
    environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: gonac/user-profile-service
    restart: always
    depends_on:
      - config-service
    ports:
     - 8101:8101