spring:
  profiles:
    active: development
---

spring:
  profiles: development
---

spring:
  profiles: production
---

spring:
  application:
    name: local-search-service

server:
  port: ${PORT:7777}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

rest:
  api:
    localPath: C:\Users\Durszlak\Desktop\Uczelnia\Hy\pip2018\
    infoLanguage: en




