spec:
  template:
    spec:
      volumes:
      - name: registry
        persistentVolumeClaim:
          claimName: registry
      - name: conf
        secret:
          secretName: ${project.artifactId}-conf
      initContainers:
      # we use an init container to populate the registry
      # with some default tenants and credentials
      - name: copy-example-data
        image: busybox
        volumeMounts:
        - name: conf
          mountPath: /tmp/hono
        - name: registry
          mountPath: /var/lib/hono/device-registry
        command:
        - sh
        - -c
        - 'cp -u /tmp/hono/example-credentials.json /var/lib/hono/device-registry/credentials.json; cp -u /tmp/hono/example-tenants.json /var/lib/hono/device-registry/tenants.json'
      containers:
      - volumeMounts:
        - name: registry
          mountPath: /var/lib/hono/device-registry
        - name: conf
          mountPath: /etc/hono
          readOnly: true
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/hono/
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: LOGGING_CONFIG
          value: classpath:logback-spring.xml
        - name: _JAVA_OPTIONS
          value: -Xmx64m
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 10
