spring:
  profiles:
    active: development
---

spring:
  profiles: development
---

spring:
  profiles: production
---

spring:
  application:
    name: hello-service

server:
  port: ${PORT:3333}

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: ${NON_SECURE_PORT:0}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  ribbon:
    eureka:
      enabled: true