# Custom properties section START
custom:
  pathToUserProperties: classpath:users.properties

# Custom properties section END

spring:
  profiles:
    active: local

# Activate /actuator
endpoints:
  hypermedia:
    enabled: true

# Application info /info
info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
    project:
      name: 'DigitalCollections: Blueprints 3: REST Webservice Server (Frontend IMPL Spring Boot)'
      groupId: de.digitalcollections.blueprints
      artifactId: rest-server-springboot
      version: 1.0.0-SNAPSHOT

# mandatory configuration
jsondoc:
  basePath: http://localhost:9000
  version: 1.0
  packages[0]: de.digitalcollections.blueprints.rest.server.controller
  #packages[1]: com.example.model
  # optional configuration
  playgroundEnabled: true
  displayMethodAs: URI

# Deactivate security for sensitive actuator endpoints (DO NOT USE ON A PUBLIC ACCESSIBLE SYSTEM!!!)
management:
  port: 9001
  security:
    enabled: false

security:
  headers:
    cache: false
    # disables pragma no-cache header

server:
  port: 9000
  server-header: "DigitalCollections Blueprint REST Server v1.0.0-SNAPSHOT"

---

# PROD
custom:
  pathToUserProperties: file:///local/users.properties
  
jsondoc:
  basePath: https://www.myrestserver.com:9000

management:
  security:
    enabled: true

spring:
  profiles: PROD