spring:
  profiles:
    active: dev
  application:
    name: simple-notes-app
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/simpleNotesDb
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  security:
    basic:
      enabled: true
    user:
      name: admin
      password: admin
      role: ADMIN

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  hbm2ddl.auto: update
  ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  show_sql: true
  format_sql: true

java:
  version: 1.8

server:
  port: 8080
  servlet:
    context-path: /
    path: /

logging:
  level:
    org.springframework.web: ERROR
    com.pracownia2018: DEBUG
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: ${java.io.tmpdir}/application.log