server:
  port: 10099
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db_fh_blog?autoReconnect=true&amp;useUnicode=true&amp;characterEncoding=utf-8
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates
    suffix: .html
  mail:
    host: smtp.163.com
    username: ----
    password: ----
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mybatis:
  type-aliases-package: com.happut.fei.pojo
  configuration:
    map-underscore-to-camel-case: true

baidu:
  sign:
    baiduid: ----
    bduss: ----



logging:
  file: logs/spring-boot-logging.log