server:
  port: 4081

    
management:
  security:
    enabled: false

hedvig:

spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
#        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
       #   auto: update
      javax:
        persistence:
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy

  jackson:
    serialization:
      write_dates_as_timestamps: false


  datasource:
    url: jdbc:postgresql://localhost:5432/bot-service
    username: postgres
    password: iambatman
    platform: POSTGRESQL
