spring:
  datasource:
    url: jdbc:postgresql://p2.cgvagyrktgj5.us-east-1.rds.amazonaws.com:5432/p2
    username: p2
    password: dudedudedudedude
    platform: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  jackson:
    serialization:
      write_dates_as_timestamps: false
logging:
  file: logs/application-debug.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.revature.project2: INFO
    org.hibernate: ERROR