#Default port is 5555
server:
  port: 5555

info:
  app:
    name: Gateway
  
endpoints:
    enabled: false
    info.enabled: true
    health.enabled: true
    metrics.enabled: true
  
management:
  security:
    enabled: false
    
authentication:
  username: ${AUTH_USER}
  password: ${AUTH_PASSWORD}
  scope: ${AUTH_SCOPE}
  grant_type: ${AUTH_GRANT}
  default_password_api: ${AUTH_DEFAULT_PASSWORD_API}
  tokenUri: http://authentication-service:8095/auth/oauth/token

zuul:
  ignored-services: "*"
  sensitiveHeaders: Authorization
  prefix:  /api
  routes : 
    dogservice:
      path: /dog/**
      url : http://dog-service:8090

    authenticationservice: 
      path: /auth/**
      url : http://authentication-service:8095

  
#Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.scc: DEBUG
            