server:
  port: 4085

logging:
  level:
    com:
      hedvig: DEBUG
management:
  security:
    enabled: false

hedvig:
  gateway:
    url: 192.168.1.5
  s3:
    content:
      url: https://s3.eu-central-1.amazonaws.com/com-hedvig-web-content/
  kafka:
    acks: all
    retries: 3
    bootstrap:
      servers: localhost:9092
      schema:
        registry:
          url: http://localhost:8081

cloud:
    aws:
      region:
        static: eu-west-1
      credentials.useDefaultAwsCredentialsChain: true
spring:
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: com.hedvig.productPricing.service.PostgresDialect
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
    hibernate:
      ddl-auto: validate
      show_sql: true
      format_sql: true
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write_dates_as_timestamps: false


  datasource:
    url: jdbc:postgresql://localhost:5432/product-pricing
    username: postgres
    password: hedvig
    platform: POSTGRESQL
