spring:
  profiles:
    active: development
---

spring:
  profiles: development
---

spring:
  profiles: production
---

spring:
  application:
    name: wikipedia-search-service

server:
  port: ${PORT:5555}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false


rest:
  api:
    srLimit: 1
    srInterWiki: true
    defaultUrl: pl.wikipedia.org/wiki/
    baseUrl: https://pl.wikipedia.org/w/api.php?action=query&list=search&srlimit={srLimit}&format=json&srinterwiki={srInterWiki}&srsearch={phrase}