cloudfoundry:
  autoscaler:
    sink:
      application-name: auto-scaler-sink-application
      threshold-maximum: 90
      threshold-minimum: 30
      instance-count-maximum: 7
      instance-count-minimum: 1
