spring:
  profiles:
    active: development
---

spring:
  profiles: development
---

spring:
  profiles: production
---

spring:
  application:
    name: aggregate-service

server:
  port: ${PORT:8888}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

client:
  wikiClient:
    enabled: true

  googleClient:
    enabled: true

  localClient:
    enabled: true

  googleDriveClient:
    enabled: true
