spring:
  profiles:
    active: development
---

spring:
  profiles: development
---

spring:
  profiles: production
---

spring:
  application:
    name: google-search-service

server:
  port: ${PORT:4444}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

rest:
  api:
    apiKey: AIzaSyDYTuoamwOqR6F7PgfuFLQFKTEahfbZ-s8
    engineId: 001821202551686213066:j5ncf6ughba
    language: lang_en
    resultsMultiplier: 1
    baseUrl: https://www.googleapis.com/customsearch/v1?key={apiKey}&cx={engineId}&lr={language}&q={query}&start={start}