spring:
  profiles:
    active: development
---

spring:
  profiles: development
---

spring:
  profiles: production
---

spring:
  application:
    name: google-drive-search-service

server:
  port: ${PORT:2301}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: ${NON_SECURE_PORT:0}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

rest:
  api:
    size: 100
    fields: nextPageToken, files(id, name, mimeType, createdTime, webViewLink, webContentLink, modifiedTime, description, iconLink, size)

prop:
  googledrive:
    url: url
    results: results
    header: header
    webViewLink: webViewLink
    webContentLink: webContentLink
    mimeType: mimeType
    createdTime: createdTime
    timestamp: timestamp
    snippet: snippet
    additionalData: additionalData
    description: description
    iconLink: iconLink
    modifiedTime: modifiedTime
    size: size
