server:
  port: 8889

---
spring:
  profiles: dev
  cloud:
    config:
      server:
        git:
          uri: file:///${GIT_REPO}


---
spring:
  profiles: cloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gonac/config
