spring:
  profiles:
    active: development
---

spring:
  profiles: development
---

spring:
  profiles: production
---

spring:
  application:
    name: turbine.stream

server:
  port: ${PORT:8989}

eureka:
  client:
    service-url.defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/

turbine:
  app-config: wikipedia-search-service,google-search-service,local-search-service,aggregate-service

  cluster-name-expression: new String("default")

  instanceUrlSuffix:
    default: /hystrix.stream