#endpoints:
#  hypermedia:
#    enabled: true

info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8
# removed (now using build-info-goal from maven plugin (see pom.xml))
#    project:
#      name: 'DigitalCollections: Blueprints 4: Webapp (Spring Boot + Thymeleaf)'
#      groupId: de.digitalcollections.blueprints
#      artifactId: webapp-springboot-thymeleaf
#      version: 1.0.0-SNAPSHOT

management:
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: '*'
#  security:
#    enabled: true
##    roles: 'ACTUATOR, SUPERUSER'
  server:
    port: 9001
#    servlet:
#      context-path: '/monitoring'

#security:
#  basic:
#    enabled: false
#  headers:
#    cache: false

spring:
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: "USER, ACTUATOR"
  thymeleaf:
    cache: false

server:
  port: 9000
  server-header: "DigitalCollections: Blueprints 4: Webapp (Spring Boot + Thymeleaf) v1.0.0-SNAPSHOT"
  servlet:
    context-path: "/"

---

#management:
#  security:
#    enabled: true

spring:
  profiles: PROD
  thymeleaf:
    cache: true